#bash .//scripts//final//h57//AMPTST.sh
#bash .//scripts//final//h57//AMPTST-head.sh
#bash .//scripts//final//h57//AMPTST-v2.sh
#bash .//scripts//final//h57//AMPTST-final.sh
#bash .//scripts//final//h57//AMPTST-v201.sh
#bash .//scripts//final//h57//AMPTST-v2-head.sh
#bash .//scripts//final//h57//AMPTST-v201-head.sh
#bash .//scripts//final//h57//AMPTST-v2-f.sh
#bash .//scripts//final//h57//AMPTST-v2-p.sh
#bash .//scripts//final//h57//AMPTST-v2-f-head.sh
#bash .//scripts//final//h57//AMPTST-v2-p-head.sh
#bash .//scripts//final//h57//AMPTST-v3.sh
bash .//scripts//final//h57//AMPTST-v301.sh
#bash .//scripts//final//h57//AMPTST-v3-head.sh
bash .//scripts//final//h57//AMPTST-v301-head.sh
bash .//scripts//final//h57//AMPTST-v301-mse.sh
#bash .//scripts//final//h57//AMPTST-v4.sh
#bash .//scripts//final//h57//AMPTST-v4-head.sh
#bash .//scripts//final//h57//DLinear.sh
#bash .//scripts//final//h57//iTransformer.sh
#bash .//scripts//final//h57//PatchTST.sh
#bash .//scripts//final//h57//TimeMixer.sh
#bash .//scripts//final//h57//TimesNet.sh