bash .\\scripts\\V3\\main_raw_96\\AMPTST.sh
bash .\\scripts\\V3\\main_raw_96\\DLinear.sh
bash .\\scripts\\V3\\main_raw_96\\iTransformer.sh
bash .\\scripts\\V3\\main_raw_96\\PatchTST.sh
bash .\\scripts\\V3\\main_raw_96\\TimeMixer.sh
bash .\\scripts\\V3\\main_raw_96\\TimesNet.sh
bash .\\scripts\\V3\\main_raw_168\\AMPTST.sh
bash .\\scripts\\V3\\main_raw_168\\DLinear.sh
bash .\\scripts\\V3\\main_raw_168\\iTransformer.sh
bash .\\scripts\\V3\\main_raw_168\\PatchTST.sh
bash .\\scripts\\V3\\main_raw_168\\TimeMixer.sh
bash .\\scripts\\V3\\main_raw_168\\TimesNet.sh